services:
  backend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./images:/app/images
      - ./results:/app/results
    environment:
      - IMAGES_FOLDER=app/images
      - RESULTS_FOLDER=app/results
      - ALLOWED_ORIGINS=http://localhost:3000

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

