spring.application.name=poke-color-matcher
allowed.origins=http://localhost:5173
results.folder=results
images.folder=images
spring.datasource.url=jdbc:h2:file:./data/searchhistory
spring.jpa.hibernate.ddl-auto=update